# Default namespace
namespace:
  environment: "poc"

# Enabling postgres service, by default
postgresql:
  # Uncomment line below and set to postgres host fqdn is using postgres outside release
  # server: postgres_host_fqdn
  database: "voting"
  username: "voting"
  password: "k2nDN2oX"
  environment: "poc"

# Default redis
redis:
  environment: "poc"

# Default result
result:
  environment: "poc"
  password: "JdUTHJjGcNastFwz"

# Default vote
vote:
  environment: "poc"

# Default worker
worker:
  environment: "poc"
